site_name: Workbench
nav:
  - Welcome: index.md
  - Presentations: presentations/index.md
  - Getting Started: getting_started/index.md
  - Workbench REPL: repl/index.md
  - API Classes: 
    - OverView: api_classes/overview.md
    - Meta: api_classes/meta.md
    - DataSource: api_classes/data_source.md
    - FeatureSet: api_classes/feature_set.md
    - Model: api_classes/model.md
    - Endpoint: api_classes/endpoint.md
    - Views: api_classes/views.md
    - Parameter Store: api_classes/parameter_store.md
    - DataFrame Store: api_classes/df_store.md
    - Pipelines: api_classes/pipelines.md
    - Monitor: api_classes/monitor.md
  - Chem Utilities:  chem_utils/index.md
  - Caching Classes:
    - OverView: cached/overview.md
    - Cached Meta: cached/cached_meta.md
    - Cached DataSource: cached/cached_data_source.md
    - Cached FeatureSet: cached/cached_feature_set.md
    - Cached Model: cached/cached_model.md
    - Cached Endpoint: cached/cached_endpoint.md
  - Theme Support:
    - Overview: themes/index.md
    - Support Phases (WIP): themes/details.md
  - Blogs: 
    - OverView: blogs/index.md
    - Residual Analysis: blogs/residual_analysis.md 
    - Exploratory Data Analysis(EDA): blogs/eda.md
    - High Target Gradients (HTG): blogs/htg.md
    - Model Monitoring: blogs/model_monitoring.md
  - Core Classes: 
    - OverView: core_classes/overview.md
    - Artifacts: 
      - OverView: core_classes/artifacts/overview.md
      - AthenaSource: core_classes/artifacts/athena_source.md
      - FeatureSetCore: core_classes/artifacts/feature_set_core.md
      - ModelCore: core_classes/artifacts/model_core.md
      - EndpointCore: core_classes/artifacts/endpoint_core.md
      - MonitorCore: core_classes/artifacts/monitor_core.md
      - Artifact: core_classes/artifacts/artifact.md
    - Views:
      - OverView: core_classes/views/overview.md
      - ComputationView: core_classes/views/computation_view.md
      - DisplayView: core_classes/views/display_view.md
      - TrainingView: core_classes/views/training_view.md
      - InferenceView: core_classes/views/inference_view.md
    - Transforms: 
      - OverView: core_classes/transforms/overview.md
      - Data Loaders Light: core_classes/transforms/data_loaders_light.md
      - Data Loaders Heavy: core_classes/transforms/data_loaders_heavy.md
      - Data To Features: core_classes/transforms/data_to_features.md
      - Features To Model: core_classes/transforms/features_to_model.md
      - Model to Endpoint: core_classes/transforms/model_to_endpoint.md
      - Pandas Transforms: core_classes/transforms/pandas_transforms.md
      - Transform: core_classes/transforms/transform.md
  - Plugins: 
      - OverView: plugins/index.md
  - Data Algorithms: 
      - OverView: data_algorithms/overview.md
      - DataFrames: data_algorithms/dataframes/overview.md
      - Graphs: data_algorithms/graphs/overview.md
      - Spark: data_algorithms/spark/overview.md
      - SQL: data_algorithms/sql/overview.md
  - Workbench Enterprise:
      - OverView: enterprise/index.md
      - Private SaaS: enterprise/private_saas.md
      - Themes: enterprise/themes.md
      - Project Branding: enterprise/project_branding.md
  - FAQ:  misc/faq.md
  - AWS Glue Jobs: glue/index.md 
  - AWS Lambda Layer: lambda_layer/index.md 
  - AWS CloudWatch: cloudwatch/index.md 
  - AWS Setup: 
    - AWS CLI/SSO Setup: aws_setup/aws_setup.md
    - Full Pipeline Testing: aws_setup/full_pipeline.md
    - AWS Admin Initial Setup: aws_setup/core_stack.md
    - Dashboard Setup: aws_setup/dashboard_stack.md
    - Domain/SSL Cert Setup: aws_setup/domain_cert_setup.md
    - AWS Tips and Tricks: aws_setup/aws_tips_and_tricks.md
    - AWS Access Management: aws_setup/aws_access_management.md
    - AWS Client VPN: aws_setup/aws_client_vpn.md
  - Road Maps: 
    - 0.9.0:  road_maps/0_9_0.md
    - 0.9.5:  road_maps/0_9_5.md
  - Release Notes: 
    - 0.8.106:  release_notes/0_8_106.md
    - 0.8.78:  release_notes/0_8_78.md
    - 0.8.74:  release_notes/0_8_74.md
    - 0.8.71:  release_notes/0_8_71.md
    - 0.8.60:  release_notes/0_8_60.md
    - 0.8.58:  release_notes/0_8_58.md
    - 0.8.55:  release_notes/0_8_55.md
    - 0.8.50:  release_notes/0_8_50.md
    - Archived:
      - 0.8.46:  release_notes/archived/0_8_46.md
      - 0.8.42:  release_notes/archived/0_8_42.md
      - 0.8.39:  release_notes/archived/0_8_39.md
      - 0.8.36:  release_notes/archived/0_8_36.md
      - 0.8.35:  release_notes/archived/0_8_35.md
      - 0.8.33:  release_notes/archived/0_8_33.md
      - 0.8.29:  release_notes/archived/0_8_29.md
      - 0.8.27:  release_notes/archived/0_8_27.md
      - 0.8.23:  release_notes/archived/0_8_23.md
      - 0.8.22:  release_notes/archived/0_8_22.md
      - 0.8.20:  release_notes/archived/0_8_20.md
      - 0.8.11:  release_notes/archived/0_8_11.md
      - 0.8.8:  release_notes/archived/0_8_8.md
      - 0.8.6:  release_notes/archived/0_8_6.md
      - 0.7.8:  release_notes/archived/0_7_8.md
  - Admin: 
    - AWS Service Limits:  admin/aws_service_limits.md
    - PyPI Release:  admin/pypi_release.md
    - Base Docker Push:  admin/base_docker_push.md
    - Dashboard Docker Push:  admin/dashboard_docker_push.md
    - Dashboard with S3 Plugins:  admin/dashboard_s3_plugins.md
    - Explorer Docker Push:  admin/explorer_docker_push.md
    - Storage:
      - Workbench Docker for Lambdas:  admin/workbench_docker_for_lambdas.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  # Palette toggle for dark mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]

dev_addr: 127.0.0.1:8001
